package transport_abreu;

import entidades.Cliente;
import entidades.DetalleFactura;
import entidades.Factura;
import entidades.Ncf;
import entidades.Ubicacion;
import java.awt.Color;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import manejo.ManejoDetalleFactura;
import manejo.ManejoFactura;
import manejo.ManejoNcf;
import manejo.ManejoUbicacion;
import reportes.Reporte;

/**
 * @author ${user}-PC:U83U06 Transporte_Abreu Hecho por : Enriquillo, Erick
 * Abreu, Chang I-hua Fecha : 2013-Primer semestre
 */
public class FacturaBeta extends javax.swing.JDialog {

    SimpleDateFormat ffecha = new SimpleDateFormat("dd-MM-yyyy");
    Object[][] array;
    Cliente cliente;
    boolean bCliente = false;
    boolean bCliente2 = false;
    Double totFac = 0.0;
    int codOri = 0;
    int codDes = 0;
    ManejoNcf mNcf = new ManejoNcf();
    ManejoUbicacion mUbicacion = new ManejoUbicacion();

    public FacturaBeta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        Locale.setDefault(new Locale("es"));
        Date date = new Date();

        setCodFactura();
        Calendar test = Calendar.getInstance();

        jTextFSemana.setText(String.valueOf(test.get(Calendar.WEEK_OF_YEAR)));
        jCBFTipo.setModel(new DefaultComboBoxModel(mNcf.getListaNcf().toArray()));
        jTCBOrigen.setModel(new DefaultComboBoxModel(mUbicacion.getListaUbicacion().toArray()));
        jTCBDestino.setModel(new DefaultComboBoxModel(mUbicacion.getListaUbicacion().toArray()));
        dpFecha.setFormats(ffecha);
        dpDFecha.setFormats(ffecha);
        dpFecha.setDate(date);
        dpDFecha.setDate(date);
        jBNuevoActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBNuevo = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLCNombre = new javax.swing.JLabel();
        jLCRnc = new javax.swing.JLabel();
        jLCDireccion = new javax.swing.JLabel();
        jLCTelefono = new javax.swing.JLabel();
        jTextCRnc = new javax.swing.JTextField();
        jTextCDireccion = new javax.swing.JTextField();
        jTextCTelefono = new javax.swing.JTextField();
        jTextCNombre = new javax.swing.JTextField();
        jLCliente = new javax.swing.JLabel();
        jBBuscarCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLFTipo = new javax.swing.JLabel();
        jLFNumero = new javax.swing.JLabel();
        jLFFecha = new javax.swing.JLabel();
        jLFSemana = new javax.swing.JLabel();
        jTextFNumero = new javax.swing.JTextField();
        jTextFSemana = new javax.swing.JTextField();
        jCBFTipo = new javax.swing.JComboBox();
        dpFecha = new org.jdesktop.swingx.JXDatePicker();
        jLFactura = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDetalleFactura = new javax.swing.JTable();
        jTNumContenedor = new javax.swing.JTextField();
        jTNumConduce = new javax.swing.JTextField();
        jTTipoCarga = new javax.swing.JTextField();
        jTValor = new javax.swing.JTextField();
        jTAgregar = new javax.swing.JButton();
        jTQuitar = new javax.swing.JButton();
        jBGuardar1 = new javax.swing.JButton();
        dpDFecha = new org.jdesktop.swingx.JXDatePicker();
        jTCBOrigen = new javax.swing.JComboBox();
        jTCBDestino = new javax.swing.JComboBox();
        jLTotal = new javax.swing.JLabel();
        jTextTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLNcf = new javax.swing.JLabel();
        jLRnc = new javax.swing.JLabel();
        dLNcf = new javax.swing.JLabel();
        dLRnc = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturacion");
        setForeground(java.awt.Color.white);

        jToolBar1.setRollover(true);

        jBNuevo.setText("Nuevo");
        jBNuevo.setFocusable(false);
        jBNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(jBNuevo);

        jBGuardar.setText("Guardar");
        jBGuardar.setFocusable(false);
        jBGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBGuardar);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jLCNombre.setText("Nombre");

        jLCRnc.setText("RNC");

        jLCDireccion.setText("Direccion");

        jLCTelefono.setText("Telefono");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLCNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLCDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLCTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLCRnc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextCRnc, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addComponent(jTextCDireccion)
                    .addComponent(jTextCTelefono)
                    .addComponent(jTextCNombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCNombre)
                    .addComponent(jTextCNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCRnc)
                    .addComponent(jTextCRnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCDireccion)
                    .addComponent(jTextCDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCTelefono)
                    .addComponent(jTextCTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLCliente.setFont(new java.awt.Font("新細明體", 0, 27)); // NOI18N
        jLCliente.setText("Cliente");

        jBBuscarCliente.setText("Buscar");
        jBBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarClienteActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        jLFTipo.setText("Tipo Factura");

        jLFNumero.setText("No. Factura");

        jLFFecha.setText("Fecha");

        jLFSemana.setText("No. Semana");

        jCBFTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBFTipoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLFNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLFFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLFSemana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFSemana, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCBFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dpFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFTipo)
                    .addComponent(jCBFTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFNumero)
                    .addComponent(jTextFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFFecha)
                    .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFSemana)
                    .addComponent(jTextFSemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLFactura.setFont(new java.awt.Font("新細明體", 0, 27)); // NOI18N
        jLFactura.setText("Factura");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));

        tbDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "No. Contenedor", "Origen", "Destino", "No. Conduce", "Tipo Carga", "Valor"
            }
        ));
        jScrollPane2.setViewportView(tbDetalleFactura);

        jTNumContenedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTNumContenedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNumContenedorKeyTyped(evt);
            }
        });

        jTNumConduce.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTNumConduce.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTNumConduceKeyTyped(evt);
            }
        });

        jTTipoCarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTTipoCarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTTipoCargaKeyTyped(evt);
            }
        });

        jTValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTValorKeyTyped(evt);
            }
        });

        jTAgregar.setText("+");
        jTAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAgregarActionPerformed(evt);
            }
        });

        jTQuitar.setText("-");
        jTQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTQuitarActionPerformed(evt);
            }
        });

        jBGuardar1.setText("Guardar");
        jBGuardar1.setFocusable(false);
        jBGuardar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBGuardar1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardar1ActionPerformed(evt);
            }
        });

        jTCBOrigen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jTCBOrigenItemStateChanged(evt);
            }
        });

        jTCBDestino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jTCBDestinoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(dpDFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTNumContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTCBOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCBDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTNumConduce, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTTipoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTValor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTQuitar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNumContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumConduce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTTipoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTAgregar)
                    .addComponent(dpDFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCBOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCBDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBGuardar1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLTotal.setText("Total");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue, java.awt.Color.blue));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo mod copia analisis.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLNcf.setText("NCF:");

        jLRnc.setText("RNC:");

        dLNcf.setText("-");

        dLRnc.setText("047-0001091-3");

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBBuscarCliente))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLNcf)
                                            .addComponent(jLRnc))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(dLRnc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dLNcf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(47, 47, 47)))))
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNcf)
                            .addComponent(dLNcf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLRnc)
                            .addComponent(dLRnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLCliente)
                            .addComponent(jBBuscarCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTotal))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        nuevo();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAgregarActionPerformed
        agregar();
    }//GEN-LAST:event_jTAgregarActionPerformed

    private void jTQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTQuitarActionPerformed
        quitar();
    }//GEN-LAST:event_jTQuitarActionPerformed

    private void jCBFTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBFTipoItemStateChanged
        if ((jCBFTipo.getSelectedItem()) != null) {
            dLNcf.setText(ManejoNcf.getNCFSiguiente((Ncf) jCBFTipo.getSelectedItem()));

        } else {
            dLNcf.setText("");
        }

    }//GEN-LAST:event_jCBFTipoItemStateChanged

    private void jBGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardar1ActionPerformed
        guardar();
    }//GEN-LAST:event_jBGuardar1ActionPerformed

    private void jBBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarClienteActionPerformed
        MantenimientoCliente test = new MantenimientoCliente(this, true);
        test.setVisible(true);
        bCliente2 = true;
        cliente = test.getClient();
        if (test.getselCli() == true) {
            jTextCDireccion.setText(cliente.getDireccion());
            jTextCNombre.setText(cliente.getNombre());
            jTextCRnc.setText(cliente.getIdentificacion());
            jTextCTelefono.setText(cliente.getTelefono());
            bCliente = true;
        }
    }//GEN-LAST:event_jBBuscarClienteActionPerformed

    private void jTCBOrigenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jTCBOrigenItemStateChanged
        if (((Ubicacion) jTCBOrigen.getSelectedItem()) != null) {
            codOri = mUbicacion.getCod_Ubicacion((Ubicacion) jTCBOrigen.getSelectedItem());
        }
    }//GEN-LAST:event_jTCBOrigenItemStateChanged

    private void jTCBDestinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jTCBDestinoItemStateChanged
        if (((Ubicacion) jTCBDestino.getSelectedItem()) != null) {
            codDes = mUbicacion.getCod_Ubicacion((Ubicacion) jTCBDestino.getSelectedItem());
        }
    }//GEN-LAST:event_jTCBDestinoItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Reporte.rFactura(Integer.parseInt(jTextFNumero.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTValorKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTValorKeyTyped

    private void jTTipoCargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTTipoCargaKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()) && !Character.isAlphabetic(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTTipoCargaKeyTyped

    private void jTNumConduceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNumConduceKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()) && !Character.isAlphabetic(evt.getKeyChar())) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTNumConduceKeyTyped

    private void jTNumContenedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTNumContenedorKeyTyped
        if (jTNumContenedor.getText().length() < 13) {

            if (jTNumContenedor.getText().length() == 4 || jTNumContenedor.getText().length() == 11) {
                jTNumContenedor.setText(jTNumContenedor.getText() + "-");
            }
            if (!Character.isDigit(evt.getKeyChar()) && !Character.isISOControl(evt.getKeyChar()) && !Character.isAlphabetic(evt.getKeyChar())) {
                Toolkit.getDefaultToolkit().beep();
                evt.consume();
            } else {
                if (Character.isLowerCase(evt.getKeyChar())) {
                    jTNumContenedor.setText(jTNumContenedor.getText() + Character.toUpperCase(evt.getKeyChar()));
                    evt.consume();
                }
            }

        } else {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_jTNumContenedorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaBeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaBeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaBeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaBeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FacturaBeta dialog = new FacturaBeta(new javax.swing.JFrame(), false);
                dialog.getContentPane().setBackground(Color.white);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dLNcf;
    private javax.swing.JLabel dLRnc;
    private org.jdesktop.swingx.JXDatePicker dpDFecha;
    private org.jdesktop.swingx.JXDatePicker dpFecha;
    private javax.swing.JButton jBBuscarCliente;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBGuardar1;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCBFTipo;
    private javax.swing.JLabel jLCDireccion;
    private javax.swing.JLabel jLCNombre;
    private javax.swing.JLabel jLCRnc;
    private javax.swing.JLabel jLCTelefono;
    private javax.swing.JLabel jLCliente;
    private javax.swing.JLabel jLFFecha;
    private javax.swing.JLabel jLFNumero;
    private javax.swing.JLabel jLFSemana;
    private javax.swing.JLabel jLFTipo;
    private javax.swing.JLabel jLFactura;
    private javax.swing.JLabel jLNcf;
    private javax.swing.JLabel jLRnc;
    private javax.swing.JLabel jLTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jTAgregar;
    private javax.swing.JComboBox jTCBDestino;
    private javax.swing.JComboBox jTCBOrigen;
    private javax.swing.JTextField jTNumConduce;
    private javax.swing.JTextField jTNumContenedor;
    private javax.swing.JButton jTQuitar;
    private javax.swing.JTextField jTTipoCarga;
    private javax.swing.JTextField jTValor;
    private javax.swing.JTextField jTextCDireccion;
    private javax.swing.JTextField jTextCNombre;
    private javax.swing.JTextField jTextCRnc;
    private javax.swing.JTextField jTextCTelefono;
    private javax.swing.JTextField jTextFNumero;
    private javax.swing.JTextField jTextFSemana;
    private javax.swing.JTextField jTextTotal;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbDetalleFactura;
    // End of variables declaration//GEN-END:variables
    private Object[] detalleFactura;
    private Factura factura;

    private void nuevo() {
        jCBFTipo.setSelectedIndex(-1);
        dLNcf.setText("");
        jTextCDireccion.setText("");
        jTextCNombre.setText("");
        jTextCRnc.setText("");
        jTextCTelefono.setText("");
        jTextFNumero.setText("");
        jTextTotal.setText("");
        jTCBDestino.setSelectedIndex(-1);
        jTCBOrigen.setSelectedIndex(-1);
        //jTFecha.setText("");
        jTNumConduce.setText("");
        jTNumContenedor.setText("");
        jTTipoCarga.setText("");
        jTValor.setText("");
        bCliente = false;

        int test = tbDetalleFactura.getRowCount();
        for (int i = 0; i < (test); i++) {
            DefaultTableModel model = (DefaultTableModel) tbDetalleFactura.getModel();
            model.removeRow(0);
        }

        setCodFactura();
    }

    private void agregar() {

        if (jTNumContenedor.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "El valor de Numero de contenedor esta vacio");
        } else if (((Ubicacion) jTCBOrigen.getSelectedItem()) == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "El valor de origen esta vacio");
        } else if (((Ubicacion) jTCBDestino.getSelectedItem()) == null) {
            javax.swing.JOptionPane.showMessageDialog(null, "El valor de destino esta vacio");
        } else if (codOri == codDes) {
            javax.swing.JOptionPane.showMessageDialog(null, "El origen no puede ser el destino");
        } else if (jTNumConduce.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "El valor de numero de conduce esta vacio");
        } else if (jTValor.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "El valor de valor esta vacio");
        } else if (jTTipoCarga.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null, "El valor de tipo de carga esta vacio");
        } else {
            detalleFactura = new Object[7];
            DefaultTableModel model = (DefaultTableModel) tbDetalleFactura.getModel();

            detalleFactura[0] = ffecha.format(dpDFecha.getDate());
            detalleFactura[1] = jTNumContenedor.getText();
            detalleFactura[2] = mUbicacion.getCod_Ubicacion(((Ubicacion) jTCBOrigen.getSelectedItem()));
            detalleFactura[3] = mUbicacion.getCod_Ubicacion(((Ubicacion) jTCBDestino.getSelectedItem()));
            detalleFactura[4] = jTNumConduce.getText();
            detalleFactura[5] = jTTipoCarga.getText();
            detalleFactura[6] = jTValor.getText();

            model.addRow(detalleFactura);

            totFac = totFac + Double.parseDouble(jTValor.getText());
            jTextTotal.setText(totFac.toString());
        }

    }

    private void quitar() {

        if (tbDetalleFactura.getSelectedRow() != -1) {
            int Selected = tbDetalleFactura.getSelectedRow();
            DefaultTableModel model = (DefaultTableModel) tbDetalleFactura.getModel();
            model.removeRow(Selected);
        }
    }

    private void guardar() {

        ManejoFactura mFactura = new ManejoFactura();
//      ManejoDetalleFactura mDFactura = new ManejoDetalleFactura();
        ManejoNcf mNcf = new ManejoNcf();
        Ncf ncf = (Ncf) jCBFTipo.getSelectedItem();
        DetalleFactura dFactura = new DetalleFactura();
        factura = new Factura();

        if (bCliente == true) {
            factura.setCliente(cliente);
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Debes Seleccionar un cliente");
            return;
        }
        factura.setFecha_factura(dpFecha.getDate());

        if (((Ncf) jCBFTipo.getSelectedItem()) != null) {
            factura.setNcf(ManejoNcf.getNCFSiguiente((Ncf) jCBFTipo.getSelectedItem()));
            factura.setCod_ncf((Ncf) jCBFTipo.getSelectedItem());
            mNcf.updateActual(ncf.getCodigo());
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Debes Seleccionar tipo de factura");
            return;
        }

        if (tbDetalleFactura.getRowCount() != 0) {
            List<DetalleFactura> dFact = new ArrayList<>();
            for (int i = 0; i <= (tbDetalleFactura.getRowCount() - 1); i++) {
                try {
                    Date dFacturaFecha = ffecha.parse((String) tbDetalleFactura.getValueAt(i, 0));
                    dFactura.setFecha(dFacturaFecha);
                } catch (Exception e) {
                }
                dFactura.setCod_factura(Integer.parseInt(jTextFNumero.getText()));
                dFactura.setNum_contenedor((String) tbDetalleFactura.getValueAt(i, 1));
                dFactura.setCod_origen(mUbicacion.getUbicacion(Integer.parseInt(tbDetalleFactura.getValueAt(i, 2).toString())));
                dFactura.setCod_destino(mUbicacion.getUbicacion(Integer.parseInt(tbDetalleFactura.getValueAt(i, 3).toString())));
                dFactura.setNum_conduce((String) tbDetalleFactura.getValueAt(i, 4));
                dFactura.setTipo_carga((String) tbDetalleFactura.getValueAt(i, 5));
                dFactura.setValor(Double.parseDouble((String) tbDetalleFactura.getValueAt(i, 6)));
                //mDFactura.guardarDetalleFactura(dFactura);
                dFact.add(dFactura);
            }

            factura.setDetalleFactura(dFact);
            factura.setMonto(Double.parseDouble(jTextTotal.getText()));
            factura.setItbis(0.18);
            factura.setSubtotal(Double.parseDouble(jTextTotal.getText()) + (Double.parseDouble(jTextTotal.getText()) * 0.18));

            mFactura.guardarFactura(factura);
            totFac = 0.0;
            javax.swing.JOptionPane.showMessageDialog(null, "La factura se guardo exitosamente");
            Reporte.rFactura(Integer.parseInt(jTextFNumero.getText()));
            nuevo();
        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Le falta algun campo en detalle de factura");
            return;
        }

        //factura.setDetalleFactura(mDFactura.getLDetalleFactura(Integer.parseInt(jTextFNumero.getText())));
        //Testing
//        System.out.println("===== Lista de detalle de factura =====");
//        for (DetalleFactura detalleFactura : mDFactura.getLDetalleFactura(Integer.parseInt(jTextFNumero.getText()))) {
//            System.out.println(detalleFactura.getCod_factura());
//            System.out.println(detalleFactura.getFecha());
//            System.out.println(detalleFactura.getCod_tipo_carga());
//            System.out.println(detalleFactura.getCod_origen());
//            System.out.println(detalleFactura.getCod_destino());
//            System.out.println(detalleFactura.getNum_conduce());
//            System.out.println(detalleFactura.getNum_contenedor());
//            System.out.println(detalleFactura.getValor());
//            System.out.println(detalleFactura.getCod_transporte());
//            System.out.println("===================");
//        }
//        jBNuevoActionPerformed(null);
    }

    private void setCodFactura() {
        ManejoFactura mFactura = new ManejoFactura();
        Factura tFactura = mFactura.getFactura(mFactura.getTotal());
        String codFactura = String.valueOf(tFactura.getCodigo() + 1);
        jTextFNumero.setText(codFactura);
    }

    public boolean getbClient2() {
        return bCliente2;
    }
}
